[book]
authors = ["Dora Akbulut"]
language = "en"
multilingual = false
src = "src"
title = "thoughtassault-blog"
[output.html.playground]
runnable = false
[output.html]
theme = "theme"
default-theme = "thoughtassault"
